public class LoopsDay1  {
    public static void main(String [] args)  {
        print200to300();
        printEvensTo1000();
     

     
    } 
    public static void print int count1 = 200; while (count1 < 301)
        {
            System.out.println(count1);
            count1 = count1 + 1;
     

     
    } 
    public static void printEvensTo1000()
    int count2 = 2; while (count2 < 1001)
        {
            System.out.println(count2);
            count2 = count2 + 2;
        }
    }
}